
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

line_length:
warning: 400
ignores_function_declarations: true
ignores_comments: true
ignores_interpolated_strings: true
ignores_urls: true
