# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'GitHubRepos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubRepos
  pod 'Alamofire', '5.0.0-rc.3'
  pod 'MBProgressHUD', '~> 1.1'
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 5.10'
  target 'GitHubReposTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '5.0.0-rc.3'
  end

  target 'GitHubReposUITests' do
    # Pods for testing
  end

end
